name: Lint on Commit
on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/**'
      - 'bug/gh-**'
      - 'issue/gh-**'
      - staging
      - master

    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - 'assets/**'
      - 'docker/**'
      - '.idea/**'
      - '.dockerignore'
      - '.gitignore'
      - '**.md'
      - 'LICENSE'
      - 'renovate.json'
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Go 1.18
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install dependencies
        run: go mod download && go get

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-${{ matrix.go-version }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.go-version }}-go-

      - name: Build project to see if it compiles
        run: make build

      - name: Format project for any formatting to apply
        run: make fmt

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --issues-exit-code=1
          only-new-issues: false
          skip-pkg-cache: true
          skip-build-cache: true
