name: Release workflow
on:
  release:
    types:
      - published
jobs:
  release:
    name: Release Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get release tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: true

      - name: Add extra metadata
        id: meta
        run: |
          echo "::set-output name=sha::$(git rev-parse --short HEAD)"
          echo "::set-output name=build-date::$(date +"%D ~ %r")"

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx/cache
          key: ${{ runner.os }}-buildx-cache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-cache-

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Login into GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login into Docker Hub
        uses: docker/login-action@v1
        with:
          username: auguwu
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push x86_64 images
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          # cache-from: type=local,src=/tmp/.buildx/cache
          # cache-to: type=local,src=/tmp/.buildx/cache
          tags: |
            auguwu/tsubasa:latest
            auguwu/tsubasa:latest-amd64
            auguwu/tsubasa:${{steps.tag.outputs.tag}}
            auguwu/tsubasa:${{steps.tag.outputs.tag}}-amd64

      - name: Build and push ARM64 images
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64
          push: true
          # cache-from: type=local,src=/tmp/.buildx/cache
          # cache-to: type=local,src=/tmp/.buildx/cache
          tags: |
            auguwu/tsubasa:latest-arm64
            auguwu/tsubasa:${{steps.tag.outputs.tag}}-arm64

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    steps:
      - name: Get release tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: true

      - name: Setup Kubernetes workflow
        run: |
          mkdir ~/.kube
          echo "${{ secrets.KUBECONFIG }}" >> ~/.kube/config

      - name: Set image tag
        run: kubectl set image deployment/tsubasa tsubasa=auguwu/tsubasa:${{steps.tag.outputs.tag}}

      - name: Deploy!
        run: kubectl rollout status deployment/tsubasa
