name: Release snapshot workflow
on:
  release:
    types:
      - prereleased
concurrency:
  group: goreleaser
  cancel-in-progress: true
permissions:
  contents: write
  packages: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go 1.18
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Login into Docker Hub
        uses: docker/login-action@v2
        with:
          username: auguwu
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login into GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist --skip-sign --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
